apiVersion: apps/v1
kind: Deployment
metadata:
  name: follei-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follei-backend
  template:
    metadata:
      labels:
        app: follei-backend
    spec:
      containers:
        - name: backend
          image: follei-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:secret@postgres:5432/follei_db"
---
apiVersion: v1
kind: Service
metadata:
  name: follei-backend
spec:
  selector:
    app: follei-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer